### ISSUE TITLE
Upgrading plugin to 5.0.1 cause error when running on IOS

### ISSUE THREAD

**Issue by louisyeoh** [nstudio/nativescript-videoplayer#177]
After upgrading the plugin to 5.0.1, running on IOS will trigger the follow error and break the app.

```
CONSOLE ERROR file: node_modules/@angular/core/fesm5/core.js:4002:0: ERROR Error: Uncaught (in promise): TypeError: undefined is not a constructor (evaluating 'new _nativescript_core__WEBPACK_IMPORTED_MODULE_0__["Property"]({
name: 'src',
valueChanged: onSrcPropertyChanged,
})')
../node_modules/nativescript-videoplayer/videoplayer-common.js(file: node_modules/nativescript-videoplayer/videoplayer-common.js:57:39)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at fn(file: src/webpack/bootstrap:120:0)
at ../node_modules/nativescript-videoplayer/videoplayer.js(file: node_modules/nativescript-videoplayer/videoplayer.ios.js:1:0)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at fn(file: src/webpack/bootstrap:120:0)
```

I confirmed that this is only on 5.0.1, reverting the plugin back to 4.2.1 works just fine. Also on 5.0.1 if i remove the line registerElement("VideoPlayer", () => Video);  , i can run the app without breaking. 

```
import { registerElement } from "@nativescript/angular";
import { Video } from 'nativescript-videoplayer';

registerElement("VideoPlayer", () => Video);
```

ns info 
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.10 version and is up to date.
✔ Component tns-core-modules has 6.5.20 version and is up to date.
✔ Component tns-ios has 6.5.3 version and is up to date.
⚠ Update available for component tns-android. Your current version is 6.5.0 and the latest available version is 6.5.3.

However when i try to install the plugin on 5.0.1, i will get the following warning after installed 
`nativescript-videoplayer requires at least version 7.0.0 of platform ios. Currently installed version is 6.5.3.
`
any ideas?

**Comment by bradmartin** [comment]
https://github.com/nstudio/nativescript-videoplayer#installation Looks like you're still on NS 6, follow the README installation. 5x of this plugin is specifically for NS7. That might be why it's breaking for you. Let me know if that helps.
